/**
 * Catálogo de serviços assistenciais usados na matriz TCLE × POP
 * (renderizada abaixo do checklist principal de Documentação).
 */
export const SERVICOS_TCLE_POP: string[] = [
  "Cirurgia Ortognática",
  "Cirurgia Reconstrutiva",
  "Cistos e Tumores Bucais",
  "Fraturas Faciais",
  "Avaliação Facial (HOF)",
  "Bichectomia",
  "Bioestimuladores de Colágeno",
  "Fios de PDO espiculados",
  "Fios de PDO liso",
  "Jato de Plasma",
  "Lipo de Papada Enzimática",
  "Lipo de Papada Mecânica",
  "Microagulhamento",
  "Otomodelação",
  "Rinomodelação",
  "Toxina Botulínica",
  "Ácido Hialurônico",
  "Bioestimulador (PLLA)",
  "Bioestimulador (Hidroxiapatita)",
  "Bioestimulador (Policaprolactona)",
  "Peeling Químico",
  "Skinbooster",
  "Hidroxiapatita Cálcio",
  "PDRN",
  "Platismo",
  "Liplift",
  "Otoplastia",
  "Blefaroplastia",
  "PMMA",
  "Cervicoplastia",
  "Fios de Nylon",
  "Alinhadores Invisíveis",
  "Alinhadores",
  "Aparelhos Fixos",
  "Aparelhos Móveis",
  "Apneia Obstrutiva do Sono",
  "Atendimento Pacientes Especiais",
  "Atendimento Hospitalizados",
  "Atendimento Pré e Pós-Operatório",
  "Atendimento Urgência",
  "Avaliação e Diagnóstico Bucal",
  "Avaliação Ortodôntica e Documentação",
  "Biópsia de Lesões Bucais",
  "Bruxismo",
  "Cirurgia Guiada 3D",
  "Cirurgia Parendodôntica",
  "Clareamento Dental",
  "Consulta Acompanhamento Infantil",
  "Contenção Ortodôntica",
  "Controle de Dor Aguda",
  "Controle de Placa/Higiene Periodontal",
  "Coroas Estéticas",
  "Correção de Mordidas",
  "Curativos de Urgência",
  "Distúrbio do Sono",
  "DTM",
  "Endodontia",
  "Enxerto Ósseo",
  "Enxerto Gengival",
  "Exodontia de Sisos",
  "Expansão Palatina",
  "Extração Dentes de Leite",
  "Extrações Simples",
  "Facetas Resina",
  "Facetas Laminadas/Lentes",
  "Facetas Porcelana",
  "Flúor",
  "Fraturas Dentárias",
  "Frenectomia",
  "Gengivoplastia",
  "Hemorragias Pós-Op",
  "Implante Dentário",
  "Infiltração ATM",
  "Laserterapia Alta/Baixa",
  "Laserterapia Dores Orofaciais",
  "Limpeza Dentária",
  "Manutenção de Implantes",
  "Oclusão (Ajustes)",
  "Orientação Higiene Bucal",
  "Ortodontia",
  "Placas Miorrelaxantes",
  "Placas Ronco/Apneia",
  "Procedimentos em UTI",
  "Prótese Fixa",
  "Prótese Parcial Removível",
  "Prótese sobre Implante",
  "Prótese Total",
  "Pulpotomia Decíduos",
  "Alisamento Radicular",
  "Remoção Pino Intrarradicular",
  "Restauração Dentária",
  "Retratamento de Canal",
  "Sedação Óxido Nitroso",
  "Sedação Venosa",
  "Selamento de Perfurações",
  "Selantes",
  "Terapia Preventiva",
  "Cáries Decíduos",
  "Gengivite e Periodontite",
  "Retração Gengival",
  "Endodôntico (Uni/Bi/Multi)",
  // Estética complementar
  "Limpeza de Pele",
  "Bioestimulador Corporal",
  "Ácido Hialurônico Corporal",
  "HIPRO",
  "Laser Adhara",
  "Lavieen",
  "Pison",
  "Radiofrequência",
  "Ultraformer III",
  "MPT",
];

export function serviceSlug(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export const serviceItemId = (kind: "tcle" | "pop", name: string) =>
  `srv_${kind}_${serviceSlug(name)}`;
